# Generated by Django 5.2.5 on 2025-09-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeManagement_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.CharField(max_length=50),
        ),
    ]
